[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
axum = "0.6.20"
tokio = { version = "1.28.1", features = ["full"] }
tracing = "0.1.37"
derive_builder = "0.12"
async-trait = "0.1.68"
miwa = { git="https://github.com/miwa-rs/miwa.git" }
